version: '3'
services:
  php:
    image: php:7.2-fpm-alpine3.8
    expose:
    - 9000
    volumes:
    - ./:/var/www/html
  nginx:
    image: nginx:1.16-alpine
    volumes:
    - ./:/etc/nginx/html
    - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"